"""
Seed curated tool whitelist for Kang Chiao AI Navigator.

Sources of names: ai工具label參考.md
URLs / freeStatus / bilingual blurbs: curated draft for Internal Prototype.
Unverified fields are marked unknown / needs_review — do not invent facts at crawl time.
Difficulty stars (1–5): subjective teaching-use learning curve (5 = steeper).
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date

from kangchiao_data.schema import difficulty_label, loc


TODAY = date.today().isoformat()

# Subjective difficulty for educators/students first-use barrier.
# 1 = open and use quickly; 5 = needs setup, prompt skill, or domain knowledge.


def _tool(
    *,
    id: str,
    name: str,
    categories: list[str],
    tasks: list[str],
    roles: list[str],
    levels: list[str],
    languages: list[str],
    free_status: str,
    stars: int,
    zh: str,
    en: str,
    official_url: str | None,
    aliases: list[str] | None = None,
    google_login: bool | str = "unknown",
    requires_account: bool | str = "unknown",
    status: str = "active",
    education_url: str | None = None,
    priority_core: bool = False,
) -> dict:
    return {
        "id": id,
        "slug": id,
        "name": name,
        "aliases": aliases or [],
        "categories": categories,
        "tasks": tasks,
        "roles": roles,
        "levels": levels,
        "languages": languages,
        "freeStatus": free_status,
        "requiresAccount": requires_account,
        "googleLogin": google_login,
        "difficultyStars": stars,
        "difficulty": difficulty_label(stars),
        "shortDescription": loc(zh, en),
        "strengths": [],
        "limitations": [],
        "privacyNotes": [
            loc(
                "請勿上傳學生真實姓名、成績或其他個資。",
                "Do not upload real student names, grades, or other personal data.",
            )
        ],
        "useCases": [],
        "officialUrl": official_url,
        "educationUrl": education_url,
        "priorityCore": priority_core,
        "sourceRefs": [
            {
                "type": "curated_seed",
                "note": "Initial whitelist seed for Internal Prototype",
                "retrievedAt": TODAY,
            }
        ],
        "lastVerifiedAt": None,
        "status": status if official_url else "needs_review",
        "pageStatus": "placeholder",
    }


SEED_TOOLS: list[dict] = [
    _tool(
        id="kuse",
        name="康軒 × Kuse",
        categories=["generative_text", "reading_research"],
        tasks=[
            "lesson_plan",
            "worksheet",
            "quiz",
            "presentation",
            "research",
            "summary",
            "translate",
            "image",
            "admin_draft",
            "fun_learn",
            "homework_help",
            "study_notes",
        ],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high"],
        languages=["zh-TW"],
        free_status="freemium",
        stars=2,
        zh="康軒 × Kuse：結合康軒教材與課綱，快速生成教案、學習單、測驗與簡報等備課素材。",
        en="Kang Hsuan × Kuse: generate lesson plans, worksheets, quizzes, and slides grounded in local textbooks.",
        official_url="https://kuse.knsh.com.tw/",
        aliases=["Kuse", "康軒Kuse", "康橋 × Kuse", "康軒 x Kuse"],
        requires_account=True,
        priority_core=True,
        education_url="https://kuse.knsh.com.tw/",
    ),
    _tool(
        id="gemini",
        name="Gemini",
        categories=["generative_text"],
        tasks=["lesson_plan", "worksheet", "quiz", "translate", "writing", "research", "tutoring"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=2,
        zh="Google 多模態對話助手，適合備課、出題、摘要與雙語教材草稿。",
        en="Google multimodal assistant for lesson prep, quizzes, summaries, and bilingual drafts.",
        official_url="https://gemini.google.com/",
        google_login=True,
        requires_account=True,
    ),
    _tool(
        id="chatgpt",
        name="ChatGPT",
        categories=["generative_text"],
        tasks=["lesson_plan", "worksheet", "quiz", "writing", "translate", "tutoring", "coding"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=2,
        zh="通用對話式 AI，適合教案草稿、寫作回饋與概念講解。",
        en="General chatbot for lesson drafts, writing feedback, and concept explanations.",
        official_url="https://chatgpt.com/",
        requires_account=True,
    ),
    _tool(
        id="magicschool",
        name="MagicSchool",
        categories=["generative_text"],
        tasks=["lesson_plan", "worksheet", "quiz", "feedback", "admin_draft"],
        roles=["teacher"],
        levels=["elementary", "middle", "high"],
        languages=["en", "zh-TW"],
        free_status="freemium",
        stars=2,
        zh="面向教師的 AI 工具集合，常見於教案、差異化教學與行政文書。",
        en="Teacher-oriented AI toolkit for lesson planning, differentiation, and admin drafts.",
        official_url="https://www.magicschool.ai/",
        requires_account=True,
        education_url="https://www.magicschool.ai/",
    ),
    _tool(
        id="edcafe",
        name="Edcafe",
        categories=["generative_text"],
        tasks=["lesson_plan", "worksheet", "quiz", "tutoring"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high"],
        languages=["zh-TW", "en"],
        free_status="unknown",
        stars=3,
        zh="教育取向的 AI 學習／備課輔助（細節待官方頁驗證）。",
        en="Education-oriented AI assistant (details pending official verification).",
        official_url="https://www.edcafe.ai/",
        status="needs_review",
    ),
    _tool(
        id="mathgpt",
        name="MathGPT",
        categories=["generative_text", "subject_specialized"],
        tasks=["tutoring", "quiz", "worksheet"],
        roles=["teacher", "student"],
        levels=["middle", "high", "university"],
        languages=["en", "zh-TW"],
        free_status="freemium",
        stars=3,
        zh="數學解題與講解取向的 AI，適合練習與步驟說明。",
        en="Math-focused AI for step-by-step practice and explanations.",
        official_url="https://math-gpt.org/",
        status="needs_review",
    ),
    _tool(
        id="vidnoz",
        name="Vidnoz AI",
        categories=["media_music"],
        tasks=["video", "presentation"],
        roles=["teacher", "student"],
        levels=["middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=3,
        zh="AI 影片／虛擬人物相關創作工具，適合短影片教材。",
        en="AI video / avatar creation tool for short instructional clips.",
        official_url="https://www.vidnoz.com/",
    ),
    _tool(
        id="sudoai",
        name="SudoAI",
        categories=["media_music"],
        tasks=["image", "video"],
        roles=["teacher", "student"],
        levels=["high", "university"],
        languages=["en", "zh-TW"],
        free_status="unknown",
        stars=4,
        zh="媒體生成類工具（官方資訊待確認，第一版標記 needs_review）。",
        en="Media generation tool (official details pending review).",
        official_url=None,
        status="needs_review",
    ),
    _tool(
        id="sora",
        name="Sora",
        categories=["media_music"],
        tasks=["video"],
        roles=["teacher", "student"],
        levels=["high", "university"],
        languages=["en"],
        free_status="paid",
        stars=4,
        zh="OpenAI 影片生成相關產品；2026-07 官方頁面出現停用說明，第一版預設不推薦。",
        en="OpenAI video product; official page indicated discontinuation as of 2026-07 crawl — excluded from default recommendations.",
        official_url="https://openai.com/sora",
        requires_account=True,
        status="deprecated",
    ),
    _tool(
        id="canva",
        name="Canva",
        categories=["media_music", "whiteboard_collab"],
        tasks=["presentation", "worksheet", "image", "poster"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=1,
        zh="設計與簡報平台，模板多，適合海報、學習單版面與簡報。",
        en="Design platform with templates for posters, worksheets, and slides.",
        official_url="https://www.canva.com/",
        education_url="https://www.canva.com/education/",
        google_login=True,
        requires_account=True,
    ),
    _tool(
        id="suno",
        name="Suno",
        categories=["media_music"],
        tasks=["music", "sound", "video"],
        roles=["teacher", "student"],
        levels=["middle", "high", "university", "elementary"],
        languages=["en", "zh-TW"],
        free_status="freemium",
        stars=2,
        zh="用文字描述就能生成歌曲與人聲，適合興趣探索、配樂靈感與創意專題。",
        en="Text-to-song generation with vocals — great for exploration, soundbeds, and creative projects.",
        official_url="https://suno.com/",
        requires_account=True,
    ),
    _tool(
        id="soundraw",
        name="Soundraw",
        categories=["media_music"],
        tasks=["music", "sound"],
        roles=["teacher", "student"],
        levels=["middle", "high", "university", "elementary"],
        languages=["en"],
        free_status="freemium",
        stars=2,
        zh="AI 音樂生成，適合影片配樂或課堂氣氛音樂（注意授權）。",
        en="AI music generation for video beds or class atmosphere (check licensing).",
        official_url="https://soundraw.io/",
    ),
    _tool(
        id="ecrettmusic",
        name="Ecrett Music",
        categories=["media_music"],
        tasks=["music", "sound"],
        roles=["teacher", "student"],
        levels=["middle", "high", "university"],
        languages=["en"],
        free_status="freemium",
        stars=2,
        zh="依情緒／場景選配的音樂素材工具。",
        en="Scene/mood-based music creation tool.",
        official_url="https://ecrettmusic.com/",
    ),
    _tool(
        id="notebooklm",
        name="NotebookLM",
        categories=["reading_research"],
        tasks=["research", "summary", "quiz", "lesson_plan"],
        roles=["teacher", "student"],
        levels=["high", "university", "middle"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=2,
        zh="依使用者提供的來源整理筆記、問答與導讀，適合教材彙整。",
        en="Grounded notes/Q&A from user-provided sources; good for material synthesis.",
        official_url="https://notebooklm.google.com/",
        google_login=True,
        requires_account=True,
    ),
    _tool(
        id="konkang_voice",
        name="康軒 AI 語音小助手",
        categories=["voice_assist"],
        tasks=["language_practice", "tutoring"],
        roles=["teacher", "student"],
        levels=["elementary", "middle"],
        languages=["zh-TW"],
        free_status="unknown",
        stars=2,
        zh="康軒相關語音輔助工具，細節與入口待校內／官方確認。",
        en="Kang Hsuan-related voice assistant; entry details pending verification.",
        official_url=None,
        aliases=["康軒AI語音小助手"],
        status="needs_review",
    ),
    _tool(
        id="padlet",
        name="Padlet",
        categories=["whiteboard_collab"],
        tasks=["collaboration", "brainstorm", "presentation"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=1,
        zh="牆板式協作，適合腦力激盪、作品牆與課堂回應。",
        en="Board-style collaboration for brainstorming and class responses.",
        official_url="https://padlet.com/",
        requires_account=True,
    ),
    _tool(
        id="curipod",
        name="Curipod",
        categories=["whiteboard_collab"],
        tasks=["lesson_plan", "quiz", "presentation", "collaboration"],
        roles=["teacher"],
        levels=["elementary", "middle", "high"],
        languages=["en"],
        free_status="freemium",
        stars=2,
        zh="互動課堂簡報／活動生成，偏教師引導的即時互動。",
        en="Interactive lesson slides/activities for live classroom engagement.",
        official_url="https://curipod.com/",
        requires_account=True,
    ),
    _tool(
        id="classpoint",
        name="ClassPoint",
        categories=["whiteboard_collab"],
        tasks=["quiz", "presentation", "collaboration"],
        roles=["teacher"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="freemium",
        stars=3,
        zh="整合於 PowerPoint 的課堂互動與評量工具。",
        en="PowerPoint-integrated classroom interaction and assessment.",
        official_url="https://www.classpoint.io/",
        requires_account=True,
    ),
    _tool(
        id="seesaw",
        name="Seesaw",
        categories=["whiteboard_collab"],
        tasks=["collaboration", "portfolio", "feedback"],
        roles=["teacher", "student"],
        levels=["elementary", "middle"],
        languages=["en", "zh-TW"],
        free_status="freemium",
        stars=2,
        zh="學習歷程與家庭連結平台，常見於小學作品蒐集。",
        en="Learning journal / family connection platform, common in elementary.",
        official_url="https://seesaw.me/",
        requires_account=True,
    ),
    _tool(
        id="google_sites",
        name="Google Sites",
        categories=["whiteboard_collab"],
        tasks=["presentation", "portfolio", "collaboration"],
        roles=["teacher", "student"],
        levels=["middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="free",
        stars=2,
        zh="用學校 Google 帳號快速建立單元網頁或成果頁。",
        en="Build unit or portfolio sites quickly with a Google account.",
        official_url="https://sites.google.com/",
        google_login=True,
        requires_account=True,
    ),
    _tool(
        id="freeform",
        name="無邊記",
        categories=["whiteboard_collab"],
        tasks=["brainstorm", "collaboration", "presentation"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="free",
        stars=2,
        zh="Apple 無邊記（Freeform）白板，適合腦力激盪與視覺整理。",
        en="Apple Freeform whiteboard for brainstorming and visual organization.",
        official_url="https://support.apple.com/guide/freeform/welcome/mac",
        aliases=["Freeform", "Apple Freeform"],
        status="needs_review",
    ),
    _tool(
        id="stellarium",
        name="Stellarium",
        categories=["subject_specialized"],
        tasks=["simulation", "tutoring"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW", "en"],
        free_status="free",
        stars=3,
        zh="天文星空模擬，適合地球科學／天文單元。",
        en="Planetarium simulation for earth science / astronomy units.",
        official_url="https://stellarium.org/",
    ),
    _tool(
        id="brainingcamp",
        name="BrainingCamp",
        categories=["subject_specialized"],
        tasks=["simulation", "worksheet", "tutoring"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high"],
        languages=["en"],
        free_status="paid",
        stars=3,
        zh="數學虛擬教具與互動操作，適合概念具體化。",
        en="Virtual math manipulatives for concrete concept building.",
        official_url="https://www.brainingcamp.com/",
        status="needs_review",
    ),
    _tool(
        id="hyread",
        name="HyRead",
        categories=["subject_specialized", "reading_research"],
        tasks=["reading", "research"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high", "university"],
        languages=["zh-TW"],
        free_status="unknown",
        stars=2,
        zh="華文電子書／圖書館閱讀服務（校園方案依單位而異）。",
        en="Chinese ebook / library reading service (campus plans vary).",
        official_url="https://www.hyread.com.tw/",
    ),
    _tool(
        id="xiaoshengtong",
        name="曉聲通",
        categories=["subject_specialized", "voice_assist"],
        tasks=["language_practice", "reading"],
        roles=["teacher", "student"],
        levels=["elementary", "middle", "high"],
        languages=["zh-TW"],
        free_status="unknown",
        stars=3,
        zh="語音／朗讀相關教育工具（官方入口待確認）。",
        en="Speech/reading education tool (official entry pending).",
        official_url=None,
        status="needs_review",
    ),
    _tool(
        id="cursor",
        name="Cursor",
        categories=["generative_text", "devtools"],
        tasks=["coding", "web_project", "tutoring"],
        roles=["teacher", "student"],
        levels=["high", "university", "middle"],
        languages=["en", "zh-TW"],
        free_status="freemium",
        stars=4,
        zh="AI 程式編輯器，適合資訊課專題、網頁專案與教師開發教材腳本。",
        en="AI code editor for CS projects, web builds, and teachers scripting teaching tools.",
        official_url="https://cursor.com/",
        requires_account=True,
    ),
    _tool(
        id="claude_code",
        name="Claude Code",
        categories=["generative_text", "devtools"],
        tasks=["coding", "web_project", "tutoring"],
        roles=["teacher", "student"],
        levels=["high", "university"],
        languages=["en"],
        free_status="paid",
        stars=5,
        zh="Anthropic 代理式編碼工具，學習曲線較高，適合進階程式任務。",
        en="Anthropic agentic coding tool; steeper curve for advanced programming tasks.",
        official_url="https://www.anthropic.com/claude-code",
        aliases=["Claude Code"],
        requires_account=True,
        status="needs_review",
    ),
    _tool(
        id="codex",
        name="Codex",
        categories=["generative_text", "devtools"],
        tasks=["coding", "web_project", "tutoring"],
        roles=["teacher", "student"],
        levels=["high", "university"],
        languages=["en"],
        free_status="paid",
        stars=5,
        zh="OpenAI 編碼代理／相關產品線，適合進階開發與自動化。",
        en="OpenAI coding agent product line for advanced development workflows.",
        official_url="https://openai.com/codex/",
        requires_account=True,
        status="needs_review",
    ),
]


def build_catalog() -> dict:
    tools = deepcopy(SEED_TOOLS)
    return {
        "version": "0.1.0",
        "generatedAt": TODAY,
        "localeKeys": ["zh-TW", "en"],
        "count": len(tools),
        "tools": tools,
    }
